#!/usr/bin/env python

import sensors.camera as CAMERA
import rospy

if __name__ == '__main__':
    rospy.init_node('camera_driver')

    pub_period = rospy.get_param("~diagnostic_period",1.0)
    rate = rospy.Rate(pub_period)

    camera = CAMERA.CameraDriver()

    while not rospy.is_shutdown():
        camera.runOnce()
        rate.sleep()