#!/usr/bin/env python

import sensors.gps as GPS
import rospy

if __name__ == '__main__':
    rospy.init_node('gps_driver')

    pub_period = rospy.get_param("~diagnostic_period",1.0)
    rate = rospy.Rate(pub_period)

    gps = GPS.GPSDriver()

    while not rospy.is_shutdown():
        gps.runOnce()
        rate.sleep()