#!/usr/bin/env python

import sensors.lidar as LIDAR
import rospy

if __name__ == '__main__':
    rospy.init_node('lidar_driver')

    pub_period = rospy.get_param("~diagnostic_period",1.0)
    rate = rospy.Rate(pub_period)

    lidar = LIDAR.LidarDriver()

    while not rospy.is_shutdown():
        lidar.runOnce()
        rate.sleep()