#!/usr/bin/env python

import sensors.perception as PERCEPTION
import rospy

if __name__ == '__main__':
    rospy.init_node('perception_driver')

    pub_period = rospy.get_param("~diagnostic_period",1.0)
    rate = rospy.Rate(pub_period)

    perception = PERCEPTION.PerceptionDriver()

    while not rospy.is_shutdown():
        perception.runOnce()
        rate.sleep()